apiVersion: v1
kind: Service
metadata:
  name: statefulpoddebugservice 
spec:
  type: NodePort 
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: xvwap-order-gateway-0 
  ports:
  - protocol: TCP
    port: 40000 
